export default {
    SET_ACCOUNT_INFO : 'SET_ACCOUNT_INFO',          // 添加账号信息
    REMOVE_ACCOUNT_INFO: 'REMOVE_ACCOUNT_INFO',     // 删除账号信息
    SET_PERMISSION_DATA: 'SET_PERMISSION_DATA',     // 添加权限数据
    REMOVE_PERMISSION_DATA: 'REMOVE_PERMISSION_DATA'// 删除权限数据
}