export default {
    SET_ACCOUNT_INFO: 'SET_ACCOUNT_INFO',              // 添加账号信息
    REMOVE_ACCOUNT_INFO: 'REMOVE_ACCOUNT_INFO',         // 删除账号信息
    SET_PERMISSION_DATA: 'SET_PERMISSION_DATA',         // 添加权限数据
    SEARCH_PERMISSION_DATA: 'SEARCH_PERMISSION_DATA',   // 搜索权限数据
    CLEAR_SEARCH_PERMISSION: 'CLEAR_SEARCH_PERMISSION', // 清除权限检索信息
    REMOVE_PERMISSION_DATA: 'REMOVE_PERMISSION_DATA'    // 删除权限数据
}